# Generated by Django 2.0.4 on 2018-07-24 02:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=1000, null=True)),
                ('Article_Short_Descriptions', models.TextField(null=True)),
                ('Article_Content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('publish_date', models.DateTimeField(editable=False)),
                ('publish_by', models.CharField(max_length=250)),
                ('Category', models.CharField(editable=False, max_length=250)),
            ],
        ),
    ]
